### ISSUE TITLE
Failure to compile in Ubuntu 20.04

### ISSUE THREAD

**Issue by biologistico** [smussmann82/Comp-D_MPI#1]
Hi I'm trying to get this software installed on my PC running Ubuntu and I can't compile. After downloading the source code and running autoreconf in the directory, I get the following message when I run ./configure:

checking whether the Boost::Program_Options library is available... no

I've tried several ways to install the Boost libraries including:

sudo apt-get install libboost-dev libboost-program-options-dev libmpich2-dev autotools-dev autoconf (which fails)
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libmpich2-dev

and

sudo apt-get install libboost-dev libboost-program-options-dev libmpich-dev autotools-dev autoconf (which apparently works but then I run ./configure again and gives me the same message)

checking whether the Boost::Program_Options library is available... no

If I assume this message isn't an error and I proceed with make then I get the following:

Making all in src
make[1]: Entering directory '/home/biologistico/Comp-D_MPI-master/src'
/home/biologistico/miniconda2/bin/x86_64-conda_cos6-linux-gnu-c++ -DPACKAGE_NAME=\"compDmpi\" -DPACKAGE_TARNAME=\"compdmpi\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"compDmpi\ 1.0\" -DPACKAGE_BUGREPORT=\"mussmann@email.uark.edu\" -DPACKAGE_URL=\"\" -DPACKAGE=\"compdmpi\" -DVERSION=\"1.0\" -I.  -Wall -std=c++11 -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/biologistico/miniconda2/include  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/biologistico/miniconda2/include -MT compDmpi-dstat_main.o -MD -MP -MF .deps/compDmpi-dstat_main.Tpo -c -o compDmpi-dstat_main.o `test -f 'dstat_main.cpp' || echo './'`dstat_main.cpp
dstat_main.cpp:23:10: fatal error: boost/math/distributions/chi_squared.hpp: No such file or directory
 #include <boost/math/distributions/chi_squared.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:594: compDmpi-dstat_main.o] Error 1
make[1]: Leaving directory '/home/biologistico/Comp-D_MPI-master/src'
make: *** [Makefile:353: all-recursive] Error 1

I'm at a loss and don't know what's wrong and where. Thanks in advance for your help.

**Comment by biologistico** [comment]
I could solve the issue but now I have several errors from "undefined references to":

ompi_mpi_comm_world

MPI_Barrier

ompi_mpi_double

MPI_Gather

MPI_Finalize

MPI_Wtime


Among several others..... I'm a novice in the command line and have no experience whatsoever with C++ so I'm really confused. Thanks for your attention to the issue.

**Comment by stevemussmann** [comment]
Hi Juan,

It looks like the compiler that is being called was installed via conda. My
first steps for troubleshooting would be to either 1) disable conda, or 2)
try installing the boost libraries through conda.

-Steve

**Comment by stevemussmann** [comment]
Hi Juan,

Sorry, I didn't see your second post until now. Those errors seem to indicate that MPI is not being found. My initial troubleshooting recommendations would hold up - perhaps try installing MPI through conda (or disabling conda entirely) and see if that makes a difference.

-Steve

**Comment by biologistico** [comment]
Thanks Steve. It seems deactivating conda fixed most of the previous issues but I still got this error after running make:

mpic++  -g -O2  -lboost_program_options -lpthread  -o compDmpi compDmpi-dstat_main.o fourtax.o locusfile.o Stats.o DstatParent.o Dstat.o partD.o Dfoil.o popZParent.o popZDstat.o popZpartD.o popZDfoil.o -lboost_program_options -lpthread
/home/biologistico/miniconda2/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/biologistico/miniconda2/lib/libboost_program_options.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:545: compDmpi] Error 1
make[1]: Leaving directory '/home/biologistico/Comp-D_MPI-master/src'
make: *** [Makefile:353: all-recursive] Error 1

**Comment by biologistico** [comment]
I was finally able to install Comp-D_MPI after using

sudo apt-get install libboost-dev libboost-program-options-dev libmpich-dev autotools-dev autoconf 


and not

sudo apt-get install libboost-dev libboost-program-options-dev libmpich2-dev autotools-dev autoconf 

I'll try running my first D-statistics tests tomorrow! Thanks!

**Comment by stevemussmann** [comment]
Glad you got it working. I will add a note to the installation instructions so that others hopefully don't go through the same issues.

-Steve
